Repository AY2425S1-CS2113-W14-4/tp, pull requests merged in 2024-10, with the labels that each got.

#39 Add Ui and Printer, add Init and Exit
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/pill/Pill.java
  src/main/java/seedu/pill/command/Command.java
  src/main/java/seedu/pill/util/Printer.java
  src/main/java/seedu/pill/util/Ui.java
  src/test/java/seedu/pill/PillTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Chore, priority.High

#42 Add Parser, add basic error catching
  src/main/java/seedu/pill/Pill.java
  src/main/java/seedu/pill/command/Command.java
  src/main/java/seedu/pill/exceptions/ExceptionMessages.java
  src/main/java/seedu/pill/exceptions/PillException.java
  src/main/java/seedu/pill/util/Parser.java
  src/main/java/seedu/pill/util/Printer.java
Labels: type.Chore, priority.High

#44 Refactor exit command handling
  src/main/java/seedu/pill/Pill.java
  src/main/java/seedu/pill/util/Parser.java
Labels: priority.Low

#46 Add Item, ItemList(add/delete/edit/list), AddItemCommand, DeleteItemCommand, EditItemCommand
  src/main/java/seedu/pill/command/AddItemCommand.java
  src/main/java/seedu/pill/command/Command.java
  src/main/java/seedu/pill/command/DeleteItemCommand.java
  src/main/java/seedu/pill/command/EditItemCommand.java
  src/main/java/seedu/pill/util/Item.java
  src/main/java/seedu/pill/util/ItemList.java
Labels: priority.High

#65 User Guide V1.0
  docs/UserGuide.md
Labels: type.Chore, priority.High

#79 Refactor ItemList to ItemMap, fix minor help info typo
  src/main/java/seedu/pill/Pill.java
  src/main/java/seedu/pill/command/AddItemCommand.java
  src/main/java/seedu/pill/command/Command.java
  src/main/java/seedu/pill/command/DeleteItemCommand.java
  src/main/java/seedu/pill/command/EditItemCommand.java
  src/main/java/seedu/pill/command/FindCommand.java
  src/main/java/seedu/pill/command/HelpCommand.java
  src/main/java/seedu/pill/command/ListCommand.java
  src/main/java/seedu/pill/util/ItemList.java
  src/main/java/seedu/pill/util/ItemMap.java
  src/main/java/seedu/pill/util/Parser.java
  src/main/java/seedu/pill/util/Storage.java
  src/main/java/seedu/pill/util/Ui.java
  src/test/java/seedu/pill/command/FindCommandTest.java
  src/test/java/seedu/pill/command/ListCommandTest.java
  src/test/java/seedu/pill/util/LoadDataTest.java
Labels: type.Bug, priority.High

#81 Fix loadData exception handling, Parser exceptions, and help command …
  src/main/java/seedu/pill/Pill.java
  src/main/java/seedu/pill/command/HelpCommand.java
  src/main/java/seedu/pill/exceptions/ExceptionMessages.java
  src/main/java/seedu/pill/util/Parser.java
  src/main/java/seedu/pill/util/Storage.java
Labels: type.Bug, priority.Medium

#100 Add expiry date element
  src/main/java/seedu/pill/Pill.java
  src/main/java/seedu/pill/command/AddItemCommand.java
  src/main/java/seedu/pill/command/DeleteItemCommand.java
  src/main/java/seedu/pill/command/EditItemCommand.java
  src/main/java/seedu/pill/exceptions/ExceptionMessages.java
  src/main/java/seedu/pill/util/Item.java
  src/main/java/seedu/pill/util/ItemMap.java
  src/main/java/seedu/pill/util/Parser.java
  src/main/java/seedu/pill/util/Storage.java
  src/test/java/seedu/pill/command/FindCommandTest.java
  src/test/java/seedu/pill/command/ListCommandTest.java
  src/test/java/seedu/pill/util/LoadDataTest.java
Labels: type.Epic, priority.High

#99 HelpCommandTest // Implemented
  src/test/java/seedu/pill/command/HelpCommandTest.java
Labels: type.Chore, priority.High

#102 DateTime // Implemented
  src/main/java/seedu/pill/util/DateTime.java
Labels: type.Chore, priority.High

#106 Add "stock-check" command
  docs/DeveloperGuide.md
  src/main/java/seedu/pill/Pill.java
  src/main/java/seedu/pill/command/HelpCommand.java
  src/main/java/seedu/pill/command/StockCheckCommand.java
  src/main/java/seedu/pill/exceptions/ExceptionMessages.java
  src/main/java/seedu/pill/util/ItemMap.java
  src/main/java/seedu/pill/util/Parser.java
  src/main/java/seedu/pill/util/Printer.java
  text-ui-test/EXPECTED.TXT
Labels: type.Chore, priority.Medium

#111 #84 Handle Multi Word Input For Items and more
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/pill/exceptions/ExceptionMessages.java
  src/main/java/seedu/pill/util/ItemMap.java
  src/main/java/seedu/pill/util/Parser.java
  src/main/java/seedu/pill/util/Storage.java
  src/test/java/seedu/pill/command/AddItemCommandTest.java
Labels: type.Enhancement, priority.Medium

#112 JUnit Tests // Updated
  src/test/java/seedu/pill/command/HelpCommandTest.java
  src/test/java/seedu/pill/util/DateTimeTest.java
  src/test/java/seedu/pill/util/StringMatcherTest.java
Labels: priority.Low

#116 HelpCommand & HelpCommandTest // Updated
  src/main/java/seedu/pill/command/HelpCommand.java
  src/test/java/seedu/pill/command/HelpCommandTest.java
Labels: priority.High

#117 New Classes & Updated Classes
  src/main/java/seedu/pill/command/HelpCommand.java
  src/main/java/seedu/pill/util/DateTime.java
  src/main/java/seedu/pill/util/Order.java
  src/main/java/seedu/pill/util/OrderItem.java
  src/main/java/seedu/pill/util/StringMatcher.java
  src/main/java/seedu/pill/util/Transaction.java
  src/main/java/seedu/pill/util/TransactionManager.java
Labels: type.Enhancement, priority.High

#118 JUnit Test Classes // Implemented & Updated
  src/test/java/seedu/pill/command/HelpCommandTest.java
  src/test/java/seedu/pill/util/OrderItemTest.java
  src/test/java/seedu/pill/util/OrderTest.java
  src/test/java/seedu/pill/util/TransactionManagerTest.java
  src/test/java/seedu/pill/util/TransactionTest.java
Labels: type.Chore, priority.High

#122 Add additional test cases for command-type classes.
  src/main/java/seedu/pill/command/ExpiredCommand.java
  src/main/java/seedu/pill/command/ExpiringCommand.java
  src/test/java/seedu/pill/command/AddItemCommandTest.java
  src/test/java/seedu/pill/command/CommandTest.java
  src/test/java/seedu/pill/command/DeleteItemCommandTest.java
  src/test/java/seedu/pill/command/EditItemCommandTest.java
  src/test/java/seedu/pill/command/ExpiredCommandTest.java
  src/test/java/seedu/pill/command/ExpiringCommandTest.java
  src/test/java/seedu/pill/command/FindCommandTest.java
  src/test/java/seedu/pill/command/HelpCommandTest.java
  src/test/java/seedu/pill/command/ListCommandTest.java
  src/test/java/seedu/pill/command/StockCheckCommandTest.java
Labels: priority.High
